[package]
name = "rusty-parfums"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
fantoccini = "0.21.2"
json = "0.12.4"
reqwest = { version = "0.12.9", features = ["blocking"] }
scraper = "0.22.0"
tokio = "1.42.0"
